lr: 0.0001 #learning_rate
bs: 32 #batch_size
n_eps: 100 #num_epochs
model: deepSFNS
loss: ASL
# lowSNRNet-BCE(CNN)  subspaceNet-RMSPE(CNN)  daMUSIC-RMSPE(RNN)  deepSSE-ASL(CNN)  deepSFNS-ASL(RNN)  IQResNet-BCE(CNN)   MUSIC  B_MUSIC  SourceNumEstimator-Softmax DaMUSICSourceNumEstimator-Softmax  DeepSFNSSourceNumEstimator-Softmax
#deep learning based signal focusing and noise suppression (deepSFNS) is BeamformNet